# Generated by Django 4.0.2 on 2023-09-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownshop', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
